name: Test coteafs-listeners project

on:
  push:
    branches:
      - master
      - main
      - issue-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Test execution
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test